server:
  port: 8866
  servlet:
    context-path: /zk-order

spring:
  application:
    # 服务名称
    name: zk-order
  cloud:
    zookeeper:
      # 注册到zookeeper的地址
      connect-string: 192.168.19.128:2181
