spring:
  application:
    name: api-user-impl

server:
  port: 8201

eureka:
#  instance:
#    hostname: 127.0.0.1
  client:
#    注册到注册中心
    registerWithEureka: true
#    需要从eureka获取注册信息
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
