spring:
  application:
    name: user-client

server:
  port: 8762
  servlet:
    context-path: /user

eureka:
#  instance:
#    hostname: 127.0.0.1
  client:
#    注册到注册中心
    registerWithEureka: true
#    需要从eureka获取注册信息
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      # 服务注册中心使用集群方式的配置
#      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

